global using BasicBudgetR.Core;
global using BasicBudgetR.Core.Enums;
global using BasicBudgetR.Core.Models;
global using BasicBudgetR.Server.Application.Common;
global using BasicBudgetR.Server.Domain.Entities;
global using BasicBudgetR.Server.Domain.Entities.ReferenceEntities;
global using BasicBudgetR.Server.Infrastructure.Data;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
