global using BudgetR.Core;
global using BudgetR.Core.Extensions;
global using BudgetR.Core.Models;
global using BudgetR.Server.Application.Common;
global using BudgetR.Server.Domain.Entities;
global using BudgetR.Server.Infrastructure.Data.BudgetR;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using FluentValidation;
