// <auto-generated />
using System;
using BasicBudgetR.Server.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicBudgetR.Server.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BudgetRDbContext))]
    [Migration("20230826000321_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.Account", b =>
                {
                    b.Property<long>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AccountId"));

                    b.Property<long>("AccountTypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(4);

                    b.Property<decimal>("Balance")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)")
                        .HasColumnOrder(2);

                    b.Property<int>("BalanceType")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Name")
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)")
                        .HasColumnOrder(1);

                    b.HasKey("AccountId");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("BusinessTransactionActivityId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Accounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Account_Balance", "[Balance] >= 0");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AccountHistory");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("ModifiedAt")
                                    .HasColumnName("ModifiedAt");
                            }));
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.BusinessTransactionActivity", b =>
                {
                    b.Property<long>("BusinessTransactionActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BusinessTransactionActivityId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.HasKey("BusinessTransactionActivityId");

                    b.ToTable("BusinessTransactionActivities");

                    b.HasData(
                        new
                        {
                            BusinessTransactionActivityId = 1L,
                            CreatedAt = new DateTime(2023, 8, 26, 0, 3, 21, 388, DateTimeKind.Utc).AddTicks(973),
                            ProcessName = "Initial Seeding",
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.Household", b =>
                {
                    b.Property<long>("HouseholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HouseholdId"));

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.HasKey("HouseholdId");

                    b.HasIndex("BusinessTransactionActivityId");

                    b.ToTable("Households", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("HouseholdHistory");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("ModifiedAt")
                                    .HasColumnName("ModifiedAt");
                            }));
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.MonthBudget", b =>
                {
                    b.Property<long>("BudgetMonthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BudgetMonthId"));

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAt");

                    b.Property<long>("MonthYearId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.HasKey("BudgetMonthId");

                    b.HasIndex("BusinessTransactionActivityId");

                    b.HasIndex("MonthYearId");

                    b.ToTable("MonthBudgets", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("MonthBudgetHistory");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("ModifiedAt")
                                    .HasColumnName("ModifiedAt");
                            }));

                    b.HasData(
                        new
                        {
                            BudgetMonthId = 1L,
                            MonthYearId = 1L
                        },
                        new
                        {
                            BudgetMonthId = 2L,
                            MonthYearId = 2L
                        },
                        new
                        {
                            BudgetMonthId = 3L,
                            MonthYearId = 3L
                        },
                        new
                        {
                            BudgetMonthId = 4L,
                            MonthYearId = 4L
                        },
                        new
                        {
                            BudgetMonthId = 5L,
                            MonthYearId = 5L
                        },
                        new
                        {
                            BudgetMonthId = 6L,
                            MonthYearId = 6L
                        },
                        new
                        {
                            BudgetMonthId = 7L,
                            MonthYearId = 7L
                        },
                        new
                        {
                            BudgetMonthId = 8L,
                            MonthYearId = 8L
                        },
                        new
                        {
                            BudgetMonthId = 9L,
                            MonthYearId = 9L
                        },
                        new
                        {
                            BudgetMonthId = 10L,
                            MonthYearId = 10L
                        },
                        new
                        {
                            BudgetMonthId = 11L,
                            MonthYearId = 11L
                        },
                        new
                        {
                            BudgetMonthId = 12L,
                            MonthYearId = 12L
                        },
                        new
                        {
                            BudgetMonthId = 13L,
                            MonthYearId = 13L
                        },
                        new
                        {
                            BudgetMonthId = 14L,
                            MonthYearId = 14L
                        },
                        new
                        {
                            BudgetMonthId = 15L,
                            MonthYearId = 15L
                        },
                        new
                        {
                            BudgetMonthId = 16L,
                            MonthYearId = 16L
                        },
                        new
                        {
                            BudgetMonthId = 17L,
                            MonthYearId = 17L
                        },
                        new
                        {
                            BudgetMonthId = 18L,
                            MonthYearId = 18L
                        },
                        new
                        {
                            BudgetMonthId = 19L,
                            MonthYearId = 19L
                        },
                        new
                        {
                            BudgetMonthId = 20L,
                            MonthYearId = 20L
                        },
                        new
                        {
                            BudgetMonthId = 21L,
                            MonthYearId = 21L
                        },
                        new
                        {
                            BudgetMonthId = 22L,
                            MonthYearId = 22L
                        },
                        new
                        {
                            BudgetMonthId = 23L,
                            MonthYearId = 23L
                        },
                        new
                        {
                            BudgetMonthId = 24L,
                            MonthYearId = 24L
                        },
                        new
                        {
                            BudgetMonthId = 25L,
                            MonthYearId = 25L
                        },
                        new
                        {
                            BudgetMonthId = 26L,
                            MonthYearId = 26L
                        },
                        new
                        {
                            BudgetMonthId = 27L,
                            MonthYearId = 27L
                        },
                        new
                        {
                            BudgetMonthId = 28L,
                            MonthYearId = 28L
                        },
                        new
                        {
                            BudgetMonthId = 29L,
                            MonthYearId = 29L
                        },
                        new
                        {
                            BudgetMonthId = 30L,
                            MonthYearId = 30L
                        },
                        new
                        {
                            BudgetMonthId = 31L,
                            MonthYearId = 31L
                        },
                        new
                        {
                            BudgetMonthId = 32L,
                            MonthYearId = 32L
                        },
                        new
                        {
                            BudgetMonthId = 33L,
                            MonthYearId = 33L
                        },
                        new
                        {
                            BudgetMonthId = 34L,
                            MonthYearId = 34L
                        },
                        new
                        {
                            BudgetMonthId = 35L,
                            MonthYearId = 35L
                        },
                        new
                        {
                            BudgetMonthId = 36L,
                            MonthYearId = 36L
                        },
                        new
                        {
                            BudgetMonthId = 37L,
                            MonthYearId = 37L
                        },
                        new
                        {
                            BudgetMonthId = 38L,
                            MonthYearId = 38L
                        },
                        new
                        {
                            BudgetMonthId = 39L,
                            MonthYearId = 39L
                        },
                        new
                        {
                            BudgetMonthId = 40L,
                            MonthYearId = 40L
                        },
                        new
                        {
                            BudgetMonthId = 41L,
                            MonthYearId = 41L
                        },
                        new
                        {
                            BudgetMonthId = 42L,
                            MonthYearId = 42L
                        },
                        new
                        {
                            BudgetMonthId = 43L,
                            MonthYearId = 43L
                        },
                        new
                        {
                            BudgetMonthId = 44L,
                            MonthYearId = 44L
                        },
                        new
                        {
                            BudgetMonthId = 45L,
                            MonthYearId = 45L
                        },
                        new
                        {
                            BudgetMonthId = 46L,
                            MonthYearId = 46L
                        },
                        new
                        {
                            BudgetMonthId = 47L,
                            MonthYearId = 47L
                        },
                        new
                        {
                            BudgetMonthId = 48L,
                            MonthYearId = 48L
                        },
                        new
                        {
                            BudgetMonthId = 49L,
                            MonthYearId = 49L
                        },
                        new
                        {
                            BudgetMonthId = 50L,
                            MonthYearId = 50L
                        },
                        new
                        {
                            BudgetMonthId = 51L,
                            MonthYearId = 51L
                        },
                        new
                        {
                            BudgetMonthId = 52L,
                            MonthYearId = 52L
                        },
                        new
                        {
                            BudgetMonthId = 53L,
                            MonthYearId = 53L
                        },
                        new
                        {
                            BudgetMonthId = 54L,
                            MonthYearId = 54L
                        },
                        new
                        {
                            BudgetMonthId = 55L,
                            MonthYearId = 55L
                        },
                        new
                        {
                            BudgetMonthId = 56L,
                            MonthYearId = 56L
                        },
                        new
                        {
                            BudgetMonthId = 57L,
                            MonthYearId = 57L
                        },
                        new
                        {
                            BudgetMonthId = 58L,
                            MonthYearId = 58L
                        },
                        new
                        {
                            BudgetMonthId = 59L,
                            MonthYearId = 59L
                        },
                        new
                        {
                            BudgetMonthId = 60L,
                            MonthYearId = 60L
                        },
                        new
                        {
                            BudgetMonthId = 61L,
                            MonthYearId = 61L
                        },
                        new
                        {
                            BudgetMonthId = 62L,
                            MonthYearId = 62L
                        },
                        new
                        {
                            BudgetMonthId = 63L,
                            MonthYearId = 63L
                        },
                        new
                        {
                            BudgetMonthId = 64L,
                            MonthYearId = 64L
                        },
                        new
                        {
                            BudgetMonthId = 65L,
                            MonthYearId = 65L
                        },
                        new
                        {
                            BudgetMonthId = 66L,
                            MonthYearId = 66L
                        },
                        new
                        {
                            BudgetMonthId = 67L,
                            MonthYearId = 67L
                        },
                        new
                        {
                            BudgetMonthId = 68L,
                            MonthYearId = 68L
                        },
                        new
                        {
                            BudgetMonthId = 69L,
                            MonthYearId = 69L
                        },
                        new
                        {
                            BudgetMonthId = 70L,
                            MonthYearId = 70L
                        },
                        new
                        {
                            BudgetMonthId = 71L,
                            MonthYearId = 71L
                        },
                        new
                        {
                            BudgetMonthId = 72L,
                            MonthYearId = 72L
                        },
                        new
                        {
                            BudgetMonthId = 73L,
                            MonthYearId = 73L
                        },
                        new
                        {
                            BudgetMonthId = 74L,
                            MonthYearId = 74L
                        },
                        new
                        {
                            BudgetMonthId = 75L,
                            MonthYearId = 75L
                        },
                        new
                        {
                            BudgetMonthId = 76L,
                            MonthYearId = 76L
                        },
                        new
                        {
                            BudgetMonthId = 77L,
                            MonthYearId = 77L
                        },
                        new
                        {
                            BudgetMonthId = 78L,
                            MonthYearId = 78L
                        },
                        new
                        {
                            BudgetMonthId = 79L,
                            MonthYearId = 79L
                        },
                        new
                        {
                            BudgetMonthId = 80L,
                            MonthYearId = 80L
                        },
                        new
                        {
                            BudgetMonthId = 81L,
                            MonthYearId = 81L
                        },
                        new
                        {
                            BudgetMonthId = 82L,
                            MonthYearId = 82L
                        },
                        new
                        {
                            BudgetMonthId = 83L,
                            MonthYearId = 83L
                        },
                        new
                        {
                            BudgetMonthId = 84L,
                            MonthYearId = 84L
                        },
                        new
                        {
                            BudgetMonthId = 85L,
                            MonthYearId = 85L
                        },
                        new
                        {
                            BudgetMonthId = 86L,
                            MonthYearId = 86L
                        },
                        new
                        {
                            BudgetMonthId = 87L,
                            MonthYearId = 87L
                        },
                        new
                        {
                            BudgetMonthId = 88L,
                            MonthYearId = 88L
                        },
                        new
                        {
                            BudgetMonthId = 89L,
                            MonthYearId = 89L
                        },
                        new
                        {
                            BudgetMonthId = 90L,
                            MonthYearId = 90L
                        },
                        new
                        {
                            BudgetMonthId = 91L,
                            MonthYearId = 91L
                        },
                        new
                        {
                            BudgetMonthId = 92L,
                            MonthYearId = 92L
                        },
                        new
                        {
                            BudgetMonthId = 93L,
                            MonthYearId = 93L
                        },
                        new
                        {
                            BudgetMonthId = 94L,
                            MonthYearId = 94L
                        },
                        new
                        {
                            BudgetMonthId = 95L,
                            MonthYearId = 95L
                        },
                        new
                        {
                            BudgetMonthId = 96L,
                            MonthYearId = 96L
                        },
                        new
                        {
                            BudgetMonthId = 97L,
                            MonthYearId = 97L
                        },
                        new
                        {
                            BudgetMonthId = 98L,
                            MonthYearId = 98L
                        },
                        new
                        {
                            BudgetMonthId = 99L,
                            MonthYearId = 99L
                        },
                        new
                        {
                            BudgetMonthId = 100L,
                            MonthYearId = 100L
                        },
                        new
                        {
                            BudgetMonthId = 101L,
                            MonthYearId = 101L
                        },
                        new
                        {
                            BudgetMonthId = 102L,
                            MonthYearId = 102L
                        },
                        new
                        {
                            BudgetMonthId = 103L,
                            MonthYearId = 103L
                        },
                        new
                        {
                            BudgetMonthId = 104L,
                            MonthYearId = 104L
                        },
                        new
                        {
                            BudgetMonthId = 105L,
                            MonthYearId = 105L
                        },
                        new
                        {
                            BudgetMonthId = 106L,
                            MonthYearId = 106L
                        },
                        new
                        {
                            BudgetMonthId = 107L,
                            MonthYearId = 107L
                        },
                        new
                        {
                            BudgetMonthId = 108L,
                            MonthYearId = 108L
                        },
                        new
                        {
                            BudgetMonthId = 109L,
                            MonthYearId = 109L
                        },
                        new
                        {
                            BudgetMonthId = 110L,
                            MonthYearId = 110L
                        },
                        new
                        {
                            BudgetMonthId = 111L,
                            MonthYearId = 111L
                        },
                        new
                        {
                            BudgetMonthId = 112L,
                            MonthYearId = 112L
                        },
                        new
                        {
                            BudgetMonthId = 113L,
                            MonthYearId = 113L
                        },
                        new
                        {
                            BudgetMonthId = 114L,
                            MonthYearId = 114L
                        },
                        new
                        {
                            BudgetMonthId = 115L,
                            MonthYearId = 115L
                        },
                        new
                        {
                            BudgetMonthId = 116L,
                            MonthYearId = 116L
                        },
                        new
                        {
                            BudgetMonthId = 117L,
                            MonthYearId = 117L
                        },
                        new
                        {
                            BudgetMonthId = 118L,
                            MonthYearId = 118L
                        },
                        new
                        {
                            BudgetMonthId = 119L,
                            MonthYearId = 119L
                        },
                        new
                        {
                            BudgetMonthId = 120L,
                            MonthYearId = 120L
                        });
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.MonthYear", b =>
                {
                    b.Property<long>("MonthYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MonthYearId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("MonthYearId");

                    b.ToTable("MonthYears", (string)null);

                    b.HasData(
                        new
                        {
                            MonthYearId = 1L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 2L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 3L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 4L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 5L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 6L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 7L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 8L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 9L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 10L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 11L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 12L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2023
                        },
                        new
                        {
                            MonthYearId = 13L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 14L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 29,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 15L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 16L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 17L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 18L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 19L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 20L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 21L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 22L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 23L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 24L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 25L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 26L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 27L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 28L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 29L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 30L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 31L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 32L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 33L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 34L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 35L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 36L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 37L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 38L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 39L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 40L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 41L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 42L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 43L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 44L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 45L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 46L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 47L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 48L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 49L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 50L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 51L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 52L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 53L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 54L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 55L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 56L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 57L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 58L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 59L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 60L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 61L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 62L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 29,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 63L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 64L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 65L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 66L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 67L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 68L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 69L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 70L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 71L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 72L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 73L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 74L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 75L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 76L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 77L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 78L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 79L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 80L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 81L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 82L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 83L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 84L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 85L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 86L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 87L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 88L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 89L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 90L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 91L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 92L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 93L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 94L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 95L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 96L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 97L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 98L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 99L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 100L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 101L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 102L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 103L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 104L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 105L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 106L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 107L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 108L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 109L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 110L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 29,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 111L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 112L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 113L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 114L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 115L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 116L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 117L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 118L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 119L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 120L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2032
                        });
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.ReferenceEntities.AccountType", b =>
                {
                    b.Property<long>("AccountTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AccountTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.HasKey("AccountTypeId");

                    b.ToTable("AccountTypes", (string)null);

                    b.HasData(
                        new
                        {
                            AccountTypeId = 4L,
                            Name = "Cash"
                        },
                        new
                        {
                            AccountTypeId = 2L,
                            Name = "Savings"
                        },
                        new
                        {
                            AccountTypeId = 1L,
                            Name = "Checking"
                        },
                        new
                        {
                            AccountTypeId = 3L,
                            Name = "Credit Card"
                        },
                        new
                        {
                            AccountTypeId = 5L,
                            Name = "Investment"
                        },
                        new
                        {
                            AccountTypeId = 6L,
                            Name = "Loan"
                        },
                        new
                        {
                            AccountTypeId = 7L,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("AuthId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<long>("BtaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<long?>("HouseholdId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAt");

                    b.HasKey("UserId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Users", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("UserHistory");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("ModifiedAt")
                                    .HasColumnName("ModifiedAt");
                            }));

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            BtaId = 1L,
                            DisplayName = "System"
                        });
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.Account", b =>
                {
                    b.HasOne("BasicBudgetR.Server.Domain.Entities.ReferenceEntities.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BasicBudgetR.Server.Domain.Entities.BusinessTransactionActivity", "BusinessTransactionActivity")
                        .WithMany()
                        .HasForeignKey("BusinessTransactionActivityId");

                    b.HasOne("BasicBudgetR.Server.Domain.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountType");

                    b.Navigation("BusinessTransactionActivity");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.Household", b =>
                {
                    b.HasOne("BasicBudgetR.Server.Domain.Entities.BusinessTransactionActivity", "BusinessTransactionActivity")
                        .WithMany()
                        .HasForeignKey("BusinessTransactionActivityId");

                    b.Navigation("BusinessTransactionActivity");
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.MonthBudget", b =>
                {
                    b.HasOne("BasicBudgetR.Server.Domain.Entities.BusinessTransactionActivity", "BusinessTransactionActivity")
                        .WithMany()
                        .HasForeignKey("BusinessTransactionActivityId");

                    b.HasOne("BasicBudgetR.Server.Domain.Entities.MonthYear", "MonthYear")
                        .WithMany()
                        .HasForeignKey("MonthYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessTransactionActivity");

                    b.Navigation("MonthYear");
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.User", b =>
                {
                    b.HasOne("BasicBudgetR.Server.Domain.Entities.Household", "Household")
                        .WithMany("Users")
                        .HasForeignKey("HouseholdId");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.Household", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
