// <auto-generated />
using System;
using BasicBudgetR.Server.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicBudgetR.Server.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BudgetRDbContext))]
    partial class BudgetRDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.Account", b =>
                {
                    b.Property<long>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AccountId"));

                    b.Property<long>("AccountTypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(4);

                    b.Property<decimal>("Balance")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)")
                        .HasColumnOrder(2);

                    b.Property<int>("BalanceType")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Name")
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)")
                        .HasColumnOrder(1);

                    b.HasKey("AccountId");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("BusinessTransactionActivityId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Accounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Account_Balance", "[Balance] >= 0");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AccountHistory");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("ModifiedAt")
                                    .HasColumnName("ModifiedAt");
                            }));
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.BusinessTransactionActivity", b =>
                {
                    b.Property<long>("BusinessTransactionActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BusinessTransactionActivityId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.HasKey("BusinessTransactionActivityId");

                    b.ToTable("BusinessTransactionActivities");

                    b.HasData(
                        new
                        {
                            BusinessTransactionActivityId = 1L,
                            CreatedAt = new DateTime(2023, 8, 25, 19, 6, 51, 95, DateTimeKind.Utc).AddTicks(9614),
                            ProcessName = "Initial Seeding",
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.Household", b =>
                {
                    b.Property<long>("HouseholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HouseholdId"));

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAt");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.HasKey("HouseholdId");

                    b.HasIndex("BusinessTransactionActivityId");

                    b.ToTable("Households", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("HouseholdHistory");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("ModifiedAt")
                                    .HasColumnName("ModifiedAt");
                            }));
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.ReferenceEntities.AccountType", b =>
                {
                    b.Property<long>("AccountTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AccountTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.HasKey("AccountTypeId");

                    b.ToTable("AccountTypes", (string)null);

                    b.HasData(
                        new
                        {
                            AccountTypeId = 4L,
                            Name = "Cash"
                        },
                        new
                        {
                            AccountTypeId = 2L,
                            Name = "Savings"
                        },
                        new
                        {
                            AccountTypeId = 1L,
                            Name = "Checking"
                        },
                        new
                        {
                            AccountTypeId = 3L,
                            Name = "Credit Card"
                        },
                        new
                        {
                            AccountTypeId = 5L,
                            Name = "Investment"
                        },
                        new
                        {
                            AccountTypeId = 6L,
                            Name = "Loan"
                        },
                        new
                        {
                            AccountTypeId = 7L,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("AuthId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<long>("BtaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<long?>("HouseholdId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAt");

                    b.HasKey("UserId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Users", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("UserHistory");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("ModifiedAt")
                                    .HasColumnName("ModifiedAt");
                            }));

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            BtaId = 1L,
                            DisplayName = "System"
                        });
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.Account", b =>
                {
                    b.HasOne("BasicBudgetR.Server.Domain.Entities.ReferenceEntities.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BasicBudgetR.Server.Domain.Entities.BusinessTransactionActivity", "BusinessTransactionActivity")
                        .WithMany()
                        .HasForeignKey("BusinessTransactionActivityId");

                    b.HasOne("BasicBudgetR.Server.Domain.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountType");

                    b.Navigation("BusinessTransactionActivity");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.Household", b =>
                {
                    b.HasOne("BasicBudgetR.Server.Domain.Entities.BusinessTransactionActivity", "BusinessTransactionActivity")
                        .WithMany()
                        .HasForeignKey("BusinessTransactionActivityId");

                    b.Navigation("BusinessTransactionActivity");
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.User", b =>
                {
                    b.HasOne("BasicBudgetR.Server.Domain.Entities.Household", "Household")
                        .WithMany("Users")
                        .HasForeignKey("HouseholdId");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("BasicBudgetR.Server.Domain.Entities.Household", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
